### ISSUE TITLE
Include liblinear matlab directory

### ISSUE THREAD

**Issue by kmatzen** [yaoliUoA/MDPM#2]
Seems like you need to add the path to liblinear's matlab directory somewhere.  classify failed without doing this.  grepping through your code shows that you don't actually use `conf.pathToLiblinear` anywhere.

```
addpath([conf.pathToLiblinear 'matlab'])
```

**Comment by yaoliUoA** [comment]
The patch is added in the init.m file

**Comment by yaoliUoA** [comment]
The path is added in the init.m file
