### ISSUE TITLE
Undefined function or variable 'caffe'. 

### ISSUE THREAD

**Issue by fzvincent** [yaoliUoA/MDPM#3]
```
>> demo
Extracting cnn feature from class 1
Warning: Function version has the same name as a MATLAB builtin. We suggest you rename the function to avoid a
potential name conflict. 
> In path (line 109)
  In addpath (line 88)
  In cnnFeaExtraction (line 4)
  In demo (line 24) 
Undefined function or variable 'caffe'.

Error in cnnFeaExtraction (line 24)
caffe('init',model_def_file,model_file,'test');

Error in demo (line 24)
    cnnFeaExtraction(i);
```
1. I thought there is something is wrong with the "make matcaffe",.

```
vincent@vincent-HP-ProDesk-480-G2-MT:~/matlab/caffe$ make matcaffe
make: Nothing to be done for `matcaffe'.
```

I also think I have make matcaffe done. 
1. And have /caffe/matlab/+caffe instead of /caffe/matlab/caffe

And last, I could run the demo of MNIST of caffe.
1. I am not fairly understand  what "KSVDS-Box v11: as we use the im2colstep function in this toolbox, you need to download and compile it (im2colstep is found in ksvdsbox11/private)."  meas?
   Is it means " mex im2colstep.c"?

I am totally confuse where is wrong.

**Comment by yaoliUoA** [comment]
Hi,  I have updated our code to support the lastest caffe version. There should be no problems now.
